### PR TITLE
Support unicode headers in loader

### PR DESCRIPTION
**Pull request by metaodi**
Related to #28 and #14

### CODE REVIEW

**Comment by davidread** [comment]
This is looking great.

I've started a discussion of further enhancement here: https://github.com/ckan/ideas-and-roadmap/issues/210

**Comment by metaodi** [comment]
@davidread I finally got it to work. The build fails with a mismatch in the full_text column. Maybe there is a difference between the values in master and 2.7? I don't know.

This PR now contains several improvements:
- Transliterate unicode characters to ascii for column names
- Truncate column names at 63 characters (PostgreSQL limit)
- Guess the delimiter used in the CSV
- Fix the travis build setup

**Comment by davidread** [comment]
This is all superb!

**Comment by camfindlay** [comment]
+1 good stuff

**Pull request merged**
